import type { Metadata } from "next";
import { Inter } from "next/font/google"; 
import "./globals.css";
import AuthProvider from "./AuthProvider";
import { Toaster } from "react-hot-toast";
import { getServerSession } from "next-auth";
import Loader from "../components/loadeing/Loader";




const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased bg-[#f6f9fc]`}
      >
        <AuthProvider session={session}>
          <Loader />
          <Toaster position="top-right" />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
